//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.21 at 01:36:01 PM IST 
//


package com.baxter.idc.masterDataManager;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getElementsById complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getElementsById">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vocabularyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="elementIds" type="{http://www.ibm.com/xmlns/prod/ts/mdm/}MasterDataElementIds"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getElementsById", propOrder = {
    "vocabularyName",
    "elementIds"
})
public class GetElementsById {

    @XmlElement(required = true)
    protected String vocabularyName;
    @XmlElement(required = true)
    protected MasterDataElementIds elementIds;

    /**
     * Gets the value of the vocabularyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVocabularyName() {
        return vocabularyName;
    }

    /**
     * Sets the value of the vocabularyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVocabularyName(String value) {
        this.vocabularyName = value;
    }

    /**
     * Gets the value of the elementIds property.
     * 
     * @return
     *     possible object is
     *     {@link MasterDataElementIds }
     *     
     */
    public MasterDataElementIds getElementIds() {
        return elementIds;
    }

    /**
     * Sets the value of the elementIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link MasterDataElementIds }
     *     
     */
    public void setElementIds(MasterDataElementIds value) {
        this.elementIds = value;
    }

}
