//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.21 at 01:36:01 PM IST 
//


package com.baxter.idc.masterDataManager;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.baxter.idc.masterDataManager package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetEntityVocabulariesResponse_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "getEntityVocabulariesResponse");
    private final static QName _GetHierarchiesResponse_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "getHierarchiesResponse");
    private final static QName _GetElements_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "getElements");
    private final static QName _GetRootNodes_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "getRootNodes");
    private final static QName _GetOrphanElementsResponse_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "getOrphanElementsResponse");
    private final static QName _GetElementsByIdResponse_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "getElementsByIdResponse");
    private final static QName _AddNodeToHierarchy_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "addNodeToHierarchy");
    private final static QName _GetElementsResponse_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "getElementsResponse");
    private final static QName _GetElementAttributesResponse_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "getElementAttributesResponse");
    private final static QName _GetChildNodes_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "getChildNodes");
    private final static QName _GetEntityVocabularies_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "getEntityVocabularies");
    private final static QName _CreateElementResponse_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "createElementResponse");
    private final static QName _UpdateElementResponse_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "updateElementResponse");
    private final static QName _IsElementInExistence_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "isElementInExistence");
    private final static QName _GetElementByIdResponse_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "getElementByIdResponse");
    private final static QName _CreateElement_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "createElement");
    private final static QName _GetChildNodesResponse_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "getChildNodesResponse");
    private final static QName _GetHierarchies_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "getHierarchies");
    private final static QName _GetElementsById_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "getElementsById");
    private final static QName _GetElementAttributes_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "getElementAttributes");
    private final static QName _GetElementAttributesMetadataResponse_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "getElementAttributesMetadataResponse");
    private final static QName _GetRootNodesResponse_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "getRootNodesResponse");
    private final static QName _AddNodeToHierarchyResponse_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "addNodeToHierarchyResponse");
    private final static QName _GetElementAttributesMetadata_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "getElementAttributesMetadata");
    private final static QName _AddRootNodeToHierarchy_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "addRootNodeToHierarchy");
    private final static QName _RemoveNodesFromHierarchy_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "removeNodesFromHierarchy");
    private final static QName _GetElementById_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "getElementById");
    private final static QName _MasterDataManagerFault_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "MasterDataManagerFault");
    private final static QName _RemoveNodesFromHierarchyResponse_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "removeNodesFromHierarchyResponse");
    private final static QName _GetOrphanElements_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "getOrphanElements");
    private final static QName _GetMasterDataObjectsResponse_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "getMasterDataObjectsResponse");
    private final static QName _AddRootNodeToHierarchyResponse_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "addRootNodeToHierarchyResponse");
    private final static QName _IsElementInExistenceResponse_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "isElementInExistenceResponse");
    private final static QName _UpdateElement_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "updateElement");
    private final static QName _GetMasterDataObjects_QNAME = new QName("http://www.ibm.com/xmlns/prod/ts/mdm/", "getMasterDataObjects");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.baxter.idc.masterDataManager
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetElementById }
     * 
     */
    public GetElementById createGetElementById() {
        return new GetElementById();
    }

    /**
     * Create an instance of {@link RemoveNodesFromHierarchyResponse }
     * 
     */
    public RemoveNodesFromHierarchyResponse createRemoveNodesFromHierarchyResponse() {
        return new RemoveNodesFromHierarchyResponse();
    }

    /**
     * Create an instance of {@link GetOrphanElements }
     * 
     */
    public GetOrphanElements createGetOrphanElements() {
        return new GetOrphanElements();
    }

    /**
     * Create an instance of {@link AddRootNodeToHierarchyResponse }
     * 
     */
    public AddRootNodeToHierarchyResponse createAddRootNodeToHierarchyResponse() {
        return new AddRootNodeToHierarchyResponse();
    }

    /**
     * Create an instance of {@link GetMasterDataObjectsResponse }
     * 
     */
    public GetMasterDataObjectsResponse createGetMasterDataObjectsResponse() {
        return new GetMasterDataObjectsResponse();
    }

    /**
     * Create an instance of {@link ImportMasterData }
     * 
     */
    public ImportMasterData createImportMasterData() {
        return new ImportMasterData();
    }

    /**
     * Create an instance of {@link IsElementInExistenceResponse }
     * 
     */
    public IsElementInExistenceResponse createIsElementInExistenceResponse() {
        return new IsElementInExistenceResponse();
    }

    /**
     * Create an instance of {@link UpdateElement }
     * 
     */
    public UpdateElement createUpdateElement() {
        return new UpdateElement();
    }

    /**
     * Create an instance of {@link GetMasterDataObjects }
     * 
     */
    public GetMasterDataObjects createGetMasterDataObjects() {
        return new GetMasterDataObjects();
    }

    /**
     * Create an instance of {@link GetHierarchies }
     * 
     */
    public GetHierarchies createGetHierarchies() {
        return new GetHierarchies();
    }

    /**
     * Create an instance of {@link GetElementsById }
     * 
     */
    public GetElementsById createGetElementsById() {
        return new GetElementsById();
    }

    /**
     * Create an instance of {@link GetElementAttributes }
     * 
     */
    public GetElementAttributes createGetElementAttributes() {
        return new GetElementAttributes();
    }

    /**
     * Create an instance of {@link GetElementAttributesMetadataResponse }
     * 
     */
    public GetElementAttributesMetadataResponse createGetElementAttributesMetadataResponse() {
        return new GetElementAttributesMetadataResponse();
    }

    /**
     * Create an instance of {@link GetRootNodesResponse }
     * 
     */
    public GetRootNodesResponse createGetRootNodesResponse() {
        return new GetRootNodesResponse();
    }

    /**
     * Create an instance of {@link AddNodeToHierarchyResponse }
     * 
     */
    public AddNodeToHierarchyResponse createAddNodeToHierarchyResponse() {
        return new AddNodeToHierarchyResponse();
    }

    /**
     * Create an instance of {@link GetElementAttributesMetadata }
     * 
     */
    public GetElementAttributesMetadata createGetElementAttributesMetadata() {
        return new GetElementAttributesMetadata();
    }

    /**
     * Create an instance of {@link AddRootNodeToHierarchy }
     * 
     */
    public AddRootNodeToHierarchy createAddRootNodeToHierarchy() {
        return new AddRootNodeToHierarchy();
    }

    /**
     * Create an instance of {@link ExportMasterData }
     * 
     */
    public ExportMasterData createExportMasterData() {
        return new ExportMasterData();
    }

    /**
     * Create an instance of {@link RemoveNodesFromHierarchy }
     * 
     */
    public RemoveNodesFromHierarchy createRemoveNodesFromHierarchy() {
        return new RemoveNodesFromHierarchy();
    }

    /**
     * Create an instance of {@link GetEntityVocabularies }
     * 
     */
    public GetEntityVocabularies createGetEntityVocabularies() {
        return new GetEntityVocabularies();
    }

    /**
     * Create an instance of {@link CreateElementResponse }
     * 
     */
    public CreateElementResponse createCreateElementResponse() {
        return new CreateElementResponse();
    }

    /**
     * Create an instance of {@link UpdateElementResponse }
     * 
     */
    public UpdateElementResponse createUpdateElementResponse() {
        return new UpdateElementResponse();
    }

    /**
     * Create an instance of {@link IsElementInExistence }
     * 
     */
    public IsElementInExistence createIsElementInExistence() {
        return new IsElementInExistence();
    }

    /**
     * Create an instance of {@link ExportMasterDataResult }
     * 
     */
    public ExportMasterDataResult createExportMasterDataResult() {
        return new ExportMasterDataResult();
    }

    /**
     * Create an instance of {@link GetElementByIdResponse }
     * 
     */
    public GetElementByIdResponse createGetElementByIdResponse() {
        return new GetElementByIdResponse();
    }

    /**
     * Create an instance of {@link CreateElement }
     * 
     */
    public CreateElement createCreateElement() {
        return new CreateElement();
    }

    /**
     * Create an instance of {@link GetChildNodesResponse }
     * 
     */
    public GetChildNodesResponse createGetChildNodesResponse() {
        return new GetChildNodesResponse();
    }

    /**
     * Create an instance of {@link GetHierarchiesResponse }
     * 
     */
    public GetHierarchiesResponse createGetHierarchiesResponse() {
        return new GetHierarchiesResponse();
    }

    /**
     * Create an instance of {@link GetEntityVocabulariesResponse }
     * 
     */
    public GetEntityVocabulariesResponse createGetEntityVocabulariesResponse() {
        return new GetEntityVocabulariesResponse();
    }

    /**
     * Create an instance of {@link GetElements }
     * 
     */
    public GetElements createGetElements() {
        return new GetElements();
    }

    /**
     * Create an instance of {@link GetRootNodes }
     * 
     */
    public GetRootNodes createGetRootNodes() {
        return new GetRootNodes();
    }

    /**
     * Create an instance of {@link ImportMasterDataResult }
     * 
     */
    public ImportMasterDataResult createImportMasterDataResult() {
        return new ImportMasterDataResult();
    }

    /**
     * Create an instance of {@link ImportReportType }
     * 
     */
    public ImportReportType createImportReportType() {
        return new ImportReportType();
    }

    /**
     * Create an instance of {@link GetOrphanElementsResponse }
     * 
     */
    public GetOrphanElementsResponse createGetOrphanElementsResponse() {
        return new GetOrphanElementsResponse();
    }

    /**
     * Create an instance of {@link GetElementsByIdResponse }
     * 
     */
    public GetElementsByIdResponse createGetElementsByIdResponse() {
        return new GetElementsByIdResponse();
    }

    /**
     * Create an instance of {@link AddNodeToHierarchy }
     * 
     */
    public AddNodeToHierarchy createAddNodeToHierarchy() {
        return new AddNodeToHierarchy();
    }

    /**
     * Create an instance of {@link GetElementsResponse }
     * 
     */
    public GetElementsResponse createGetElementsResponse() {
        return new GetElementsResponse();
    }

    /**
     * Create an instance of {@link GetElementAttributesResponse }
     * 
     */
    public GetElementAttributesResponse createGetElementAttributesResponse() {
        return new GetElementAttributesResponse();
    }

    /**
     * Create an instance of {@link GetChildNodes }
     * 
     */
    public GetChildNodes createGetChildNodes() {
        return new GetChildNodes();
    }

    /**
     * Create an instance of {@link MasterDataHierarchy }
     * 
     */
    public MasterDataHierarchy createMasterDataHierarchy() {
        return new MasterDataHierarchy();
    }

    /**
     * Create an instance of {@link MasterDataObject }
     * 
     */
    public MasterDataObject createMasterDataObject() {
        return new MasterDataObject();
    }

    /**
     * Create an instance of {@link ElementsWrapper }
     * 
     */
    public ElementsWrapper createElementsWrapper() {
        return new ElementsWrapper();
    }

    /**
     * Create an instance of {@link MasterDataElement }
     * 
     */
    public MasterDataElement createMasterDataElement() {
        return new MasterDataElement();
    }

    /**
     * Create an instance of {@link MasterDataHierarchyNode }
     * 
     */
    public MasterDataHierarchyNode createMasterDataHierarchyNode() {
        return new MasterDataHierarchyNode();
    }

    /**
     * Create an instance of {@link MasterDataElementAttrs }
     * 
     */
    public MasterDataElementAttrs createMasterDataElementAttrs() {
        return new MasterDataElementAttrs();
    }

    /**
     * Create an instance of {@link ImportReportEntryType }
     * 
     */
    public ImportReportEntryType createImportReportEntryType() {
        return new ImportReportEntryType();
    }

    /**
     * Create an instance of {@link MasterDataElementIds }
     * 
     */
    public MasterDataElementIds createMasterDataElementIds() {
        return new MasterDataElementIds();
    }

    /**
     * Create an instance of {@link MasterDataAttr }
     * 
     */
    public MasterDataAttr createMasterDataAttr() {
        return new MasterDataAttr();
    }

    /**
     * Create an instance of {@link EntityDisplayAttr }
     * 
     */
    public EntityDisplayAttr createEntityDisplayAttr() {
        return new EntityDisplayAttr();
    }

    /**
     * Create an instance of {@link MasterDataAttrMetadata }
     * 
     */
    public MasterDataAttrMetadata createMasterDataAttrMetadata() {
        return new MasterDataAttrMetadata();
    }

    /**
     * Create an instance of {@link MasterDataVocabMetadata }
     * 
     */
    public MasterDataVocabMetadata createMasterDataVocabMetadata() {
        return new MasterDataVocabMetadata();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEntityVocabulariesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "getEntityVocabulariesResponse")
    public JAXBElement<GetEntityVocabulariesResponse> createGetEntityVocabulariesResponse(GetEntityVocabulariesResponse value) {
        return new JAXBElement<GetEntityVocabulariesResponse>(_GetEntityVocabulariesResponse_QNAME, GetEntityVocabulariesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetHierarchiesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "getHierarchiesResponse")
    public JAXBElement<GetHierarchiesResponse> createGetHierarchiesResponse(GetHierarchiesResponse value) {
        return new JAXBElement<GetHierarchiesResponse>(_GetHierarchiesResponse_QNAME, GetHierarchiesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetElements }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "getElements")
    public JAXBElement<GetElements> createGetElements(GetElements value) {
        return new JAXBElement<GetElements>(_GetElements_QNAME, GetElements.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetRootNodes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "getRootNodes")
    public JAXBElement<GetRootNodes> createGetRootNodes(GetRootNodes value) {
        return new JAXBElement<GetRootNodes>(_GetRootNodes_QNAME, GetRootNodes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetOrphanElementsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "getOrphanElementsResponse")
    public JAXBElement<GetOrphanElementsResponse> createGetOrphanElementsResponse(GetOrphanElementsResponse value) {
        return new JAXBElement<GetOrphanElementsResponse>(_GetOrphanElementsResponse_QNAME, GetOrphanElementsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetElementsByIdResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "getElementsByIdResponse")
    public JAXBElement<GetElementsByIdResponse> createGetElementsByIdResponse(GetElementsByIdResponse value) {
        return new JAXBElement<GetElementsByIdResponse>(_GetElementsByIdResponse_QNAME, GetElementsByIdResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddNodeToHierarchy }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "addNodeToHierarchy")
    public JAXBElement<AddNodeToHierarchy> createAddNodeToHierarchy(AddNodeToHierarchy value) {
        return new JAXBElement<AddNodeToHierarchy>(_AddNodeToHierarchy_QNAME, AddNodeToHierarchy.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetElementsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "getElementsResponse")
    public JAXBElement<GetElementsResponse> createGetElementsResponse(GetElementsResponse value) {
        return new JAXBElement<GetElementsResponse>(_GetElementsResponse_QNAME, GetElementsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetElementAttributesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "getElementAttributesResponse")
    public JAXBElement<GetElementAttributesResponse> createGetElementAttributesResponse(GetElementAttributesResponse value) {
        return new JAXBElement<GetElementAttributesResponse>(_GetElementAttributesResponse_QNAME, GetElementAttributesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetChildNodes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "getChildNodes")
    public JAXBElement<GetChildNodes> createGetChildNodes(GetChildNodes value) {
        return new JAXBElement<GetChildNodes>(_GetChildNodes_QNAME, GetChildNodes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEntityVocabularies }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "getEntityVocabularies")
    public JAXBElement<GetEntityVocabularies> createGetEntityVocabularies(GetEntityVocabularies value) {
        return new JAXBElement<GetEntityVocabularies>(_GetEntityVocabularies_QNAME, GetEntityVocabularies.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateElementResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "createElementResponse")
    public JAXBElement<CreateElementResponse> createCreateElementResponse(CreateElementResponse value) {
        return new JAXBElement<CreateElementResponse>(_CreateElementResponse_QNAME, CreateElementResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateElementResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "updateElementResponse")
    public JAXBElement<UpdateElementResponse> createUpdateElementResponse(UpdateElementResponse value) {
        return new JAXBElement<UpdateElementResponse>(_UpdateElementResponse_QNAME, UpdateElementResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IsElementInExistence }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "isElementInExistence")
    public JAXBElement<IsElementInExistence> createIsElementInExistence(IsElementInExistence value) {
        return new JAXBElement<IsElementInExistence>(_IsElementInExistence_QNAME, IsElementInExistence.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetElementByIdResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "getElementByIdResponse")
    public JAXBElement<GetElementByIdResponse> createGetElementByIdResponse(GetElementByIdResponse value) {
        return new JAXBElement<GetElementByIdResponse>(_GetElementByIdResponse_QNAME, GetElementByIdResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "createElement")
    public JAXBElement<CreateElement> createCreateElement(CreateElement value) {
        return new JAXBElement<CreateElement>(_CreateElement_QNAME, CreateElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetChildNodesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "getChildNodesResponse")
    public JAXBElement<GetChildNodesResponse> createGetChildNodesResponse(GetChildNodesResponse value) {
        return new JAXBElement<GetChildNodesResponse>(_GetChildNodesResponse_QNAME, GetChildNodesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetHierarchies }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "getHierarchies")
    public JAXBElement<GetHierarchies> createGetHierarchies(GetHierarchies value) {
        return new JAXBElement<GetHierarchies>(_GetHierarchies_QNAME, GetHierarchies.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetElementsById }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "getElementsById")
    public JAXBElement<GetElementsById> createGetElementsById(GetElementsById value) {
        return new JAXBElement<GetElementsById>(_GetElementsById_QNAME, GetElementsById.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetElementAttributes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "getElementAttributes")
    public JAXBElement<GetElementAttributes> createGetElementAttributes(GetElementAttributes value) {
        return new JAXBElement<GetElementAttributes>(_GetElementAttributes_QNAME, GetElementAttributes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetElementAttributesMetadataResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "getElementAttributesMetadataResponse")
    public JAXBElement<GetElementAttributesMetadataResponse> createGetElementAttributesMetadataResponse(GetElementAttributesMetadataResponse value) {
        return new JAXBElement<GetElementAttributesMetadataResponse>(_GetElementAttributesMetadataResponse_QNAME, GetElementAttributesMetadataResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetRootNodesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "getRootNodesResponse")
    public JAXBElement<GetRootNodesResponse> createGetRootNodesResponse(GetRootNodesResponse value) {
        return new JAXBElement<GetRootNodesResponse>(_GetRootNodesResponse_QNAME, GetRootNodesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddNodeToHierarchyResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "addNodeToHierarchyResponse")
    public JAXBElement<AddNodeToHierarchyResponse> createAddNodeToHierarchyResponse(AddNodeToHierarchyResponse value) {
        return new JAXBElement<AddNodeToHierarchyResponse>(_AddNodeToHierarchyResponse_QNAME, AddNodeToHierarchyResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetElementAttributesMetadata }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "getElementAttributesMetadata")
    public JAXBElement<GetElementAttributesMetadata> createGetElementAttributesMetadata(GetElementAttributesMetadata value) {
        return new JAXBElement<GetElementAttributesMetadata>(_GetElementAttributesMetadata_QNAME, GetElementAttributesMetadata.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddRootNodeToHierarchy }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "addRootNodeToHierarchy")
    public JAXBElement<AddRootNodeToHierarchy> createAddRootNodeToHierarchy(AddRootNodeToHierarchy value) {
        return new JAXBElement<AddRootNodeToHierarchy>(_AddRootNodeToHierarchy_QNAME, AddRootNodeToHierarchy.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemoveNodesFromHierarchy }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "removeNodesFromHierarchy")
    public JAXBElement<RemoveNodesFromHierarchy> createRemoveNodesFromHierarchy(RemoveNodesFromHierarchy value) {
        return new JAXBElement<RemoveNodesFromHierarchy>(_RemoveNodesFromHierarchy_QNAME, RemoveNodesFromHierarchy.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetElementById }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "getElementById")
    public JAXBElement<GetElementById> createGetElementById(GetElementById value) {
        return new JAXBElement<GetElementById>(_GetElementById_QNAME, GetElementById.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "MasterDataManagerFault")
    public JAXBElement<String> createMasterDataManagerFault(String value) {
        return new JAXBElement<String>(_MasterDataManagerFault_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemoveNodesFromHierarchyResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "removeNodesFromHierarchyResponse")
    public JAXBElement<RemoveNodesFromHierarchyResponse> createRemoveNodesFromHierarchyResponse(RemoveNodesFromHierarchyResponse value) {
        return new JAXBElement<RemoveNodesFromHierarchyResponse>(_RemoveNodesFromHierarchyResponse_QNAME, RemoveNodesFromHierarchyResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetOrphanElements }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "getOrphanElements")
    public JAXBElement<GetOrphanElements> createGetOrphanElements(GetOrphanElements value) {
        return new JAXBElement<GetOrphanElements>(_GetOrphanElements_QNAME, GetOrphanElements.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetMasterDataObjectsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "getMasterDataObjectsResponse")
    public JAXBElement<GetMasterDataObjectsResponse> createGetMasterDataObjectsResponse(GetMasterDataObjectsResponse value) {
        return new JAXBElement<GetMasterDataObjectsResponse>(_GetMasterDataObjectsResponse_QNAME, GetMasterDataObjectsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddRootNodeToHierarchyResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "addRootNodeToHierarchyResponse")
    public JAXBElement<AddRootNodeToHierarchyResponse> createAddRootNodeToHierarchyResponse(AddRootNodeToHierarchyResponse value) {
        return new JAXBElement<AddRootNodeToHierarchyResponse>(_AddRootNodeToHierarchyResponse_QNAME, AddRootNodeToHierarchyResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IsElementInExistenceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "isElementInExistenceResponse")
    public JAXBElement<IsElementInExistenceResponse> createIsElementInExistenceResponse(IsElementInExistenceResponse value) {
        return new JAXBElement<IsElementInExistenceResponse>(_IsElementInExistenceResponse_QNAME, IsElementInExistenceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "updateElement")
    public JAXBElement<UpdateElement> createUpdateElement(UpdateElement value) {
        return new JAXBElement<UpdateElement>(_UpdateElement_QNAME, UpdateElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetMasterDataObjects }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/ts/mdm/", name = "getMasterDataObjects")
    public JAXBElement<GetMasterDataObjects> createGetMasterDataObjects(GetMasterDataObjects value) {
        return new JAXBElement<GetMasterDataObjects>(_GetMasterDataObjects_QNAME, GetMasterDataObjects.class, null, value);
    }

}
